name: Deploy to EC2

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
          chmod 600 ec2_key

      - name: Connect to EC2 and run commands
        run: |
          ssh -i ec2_key -o StrictHostKeyChecking=no ubuntu@54.237.99.1 'your-command-here'
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
