name: Backend CI/CD

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_main_app.py

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        scp -r ./ ec2-user@$EC2_HOST:/home/$EC2_USER/Parcial-Arquitectura-AWS-Big-Data
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
        pwd
        ls -la
        cd /home/$EC2_USER/Parcial-Arquitectura-AWS-Big-Data
        pip install -r requirements.txt
        sudo systemctl restart backend.service
        EOF
