name: Deploy to EC2

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          # Guardar la clave privada en un archivo y corregir los saltos de línea
          echo "$EC2_PRIVATE_KEY" | sed 's/\\n/\n/g' > ec2_key
          chmod 600 ec2_key

      - name: Connect to EC2 and run commands
        run: |
          # Conectar a la instancia EC2 usando la clave privada
          ssh -i ec2_key -o StrictHostKeyChecking=no ubuntu@54.237.99.1 'echo "Connected successfully!"'
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
