name: Debug EC2 Private Key

on:
  push:
    branches:
      - backend

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check EC2 Private Key Length
        run: |
          echo "Length of EC2_PRIVATE_KEY: ${#EC2_PRIVATE_KEY}"
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}



