name: Debug EC2 Private Key

on:
  push:
    branches:
      - backend

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Partial EC2 Private Key (Safe Debug)
        run: |
          echo "Partial EC2_PRIVATE_KEY: ${EC2_PRIVATE_KEY:0:5}...${EC2_PRIVATE_KEY: -5}"
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

