name: Backend Unit Tests

on:
  push:
    branches:
      - backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

    - name: Create test-passed tag
      if: success()
      run: |
        git tag test-passed
        git push origin test-passed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
