name: Deploy to EC2

on:
  push:
    branches:
      - backend  # Cambia a la rama donde deseas desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Esto asegura que el despliegue solo se ejecute si las pruebas han pasado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.BACKEND_SSH_HOST }}
        EC2_USER: ${{ secrets.BACKEND_USER_NAME }}
        APP_DIR: /home/ubuntu/Parcial-Arquitectura-AWS-Big-Data
      run: |
        # Preparar la clave privada
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key

        # Copiar el código a la instancia EC2
        scp -o StrictHostKeyChecking=no -i ec2_key -r . ${EC2_USER}@${SERVER_IP}:${APP_DIR}

        # Reiniciar el servicio en la instancia EC2
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            cd ${APP_DIR} &&
            source env/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart flask-app.service
        '
