name: Deploy to EC2

on:
  push:
    branches:
      - backend

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.BACKEND_SSH_HOST }}
        EC2_USER: ${{ secrets.BACKEND_USER_NAME }}
        APP_DIR: /home/ubuntu/Parcial-Arquitectura-AWS-Big-Data
      run: |
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            # Acceder al directorio del proyecto
            cd Parcial-Arquitectura-AWS-Big-Data &&

            # Activar el entorno virtual si es necesario
            source env/bin/activate &&

            # Sincronizar los últimos cambios del repositorio
            git fetch --all &&
            git reset --hard origin/backend &&
            git pull origin backend &&

            # Instalar dependencias necesarias
            pip install -r requirements.txt &&

            python main_app.py
        '
