name: Deploy to EC2

on:
  push:
    tags:
      - test-passed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.BACKEND_SSH_HOST }}
        EC2_USER: ${{ secrets.BACKEND_USER_NAME }}
        APP_DIR: /home/ubuntu/Parcial-Arquitectura-AWS-Big-Data
      run: |
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key
        scp -o StrictHostKeyChecking=no -i ec2_key -r . ${EC2_USER}@${SERVER_IP}:${APP_DIR}
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            cd ${APP_DIR} &&
            source env/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart flask-app.service
        '
