name: Deploy Frontend

on:
  push:
    branches:
      - frontend  # Rama en la que quieres que se ejecute el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # O la versión de Node.js que estés usando

    - name: Install dependencies
      run: |
        npm install

    - name: Copy project to EC2 and restart server
      env:
        EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.FRONTEND_SSH_HOST }}
        EC2_USER: ${{ secrets.FRONTEND_USER_NAME }}
        APP_DIR: /home/ubuntu/Parcial-Arquitectura-AWS-Big-Data  # Cambia a la ubicación del proyecto en la instancia EC2
      run: |
        echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
        chmod 600 ec2_key
        ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            # Acceder al directorio del proyecto
            cd Parcial-Arquitectura-AWS-Big-Data &&
            cd react-app &&

            # Sincronizar los últimos cambios del repositorio
            git fetch --all &&
            git reset --hard origin/frontend &&
            git pull origin frontend &&
            
            npm run build
            sudo cp -r build/* /var/www/html/
            sudo systemctl restart apache2
        '
