name: Frontend Deploy

on:
  push:
    branches:
      - frontend  # Ejecutar solo cuando haya cambios en la rama 'frontend'

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Asegúrate de usar la versión que necesitas

      - name: Install dependencies
        run: |
          npm install

      - name: Run frontend tests
        run: |
          npm test -- --watchAll=false

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: test_frontend  # Ejecutar solo si las pruebas pasan correctamente
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH for deploy
        env:
          EC2_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_FRONT }}
          SERVER_IP: ${{ secrets.FRONTEND_SSH_HOST }}
          EC2_USER: ${{ secrets.FRONTEND_USER_NAME }}
          APP_DIR: /home/ubuntu/react-app  # Ruta donde se encuentra tu frontend en la instancia EC2
        run: |
          echo "$EC2_PRIVATE_KEY" | tr -d '\r' > ec2_key
          chmod 600 ec2_key
          ssh -o StrictHostKeyChecking=no -i ec2_key ${EC2_USER}@${SERVER_IP} '
            # Navegar al directorio del proyecto
            cd $APP_DIR &&

            # Sincronizar los últimos cambios del repositorio
            git fetch --all &&
            git reset --hard origin/frontend &&
            git pull origin frontend &&

            # Instalar dependencias
            npm install &&

            # Construir el proyecto
            npm run build &&

            # Servir el frontend usando un servidor web estático como serve o nginx
            npx serve -s build -l 3000 --daemon
          '
